Setup Java Logging Framework #17
Code4SocialGood/c4sg-services pull request #116
Opened 2017-04-08 02:51 UTC by n-machiavelli

Add logback files for dev and prod.
logback uses sl4j library.

2017-04-09 03:37 UTC, Code4SocialGood commented
1. Should we not check in `logFile.2017-04-07.log` to the repository?
2. Where will be the log file dumped? Could we create a directory just for log files?

2017-04-09 14:29 UTC, felipealvesgnu requested changes

2017-04-09 14:29 UTC, felipealves-gnu commented on src/main/java/org/c4sg/entity/User.java
> +    private String title;
Pay attention on indentation

2017-04-09 19:08 UTC, n-machiavelli commented on src/main/java/org/c4sg/entity/User.java
> +    private String title;
Oh I must have used spaces instead of a tab. Thanks.

2017-04-10 00:29 UTC, felipealves-gnu commented on src/main/java/org/c4sg/entity/User.java
> +    private String title;
solve it and push the code again

2017-04-10 13:35 UTC, felipealves-gnu commented
@n-machiavelli Can you answer @Code4SocialGood 's questions ?

2017-04-10 18:47 UTC, n-machiavelli commented
Should we not check in logFile.2017-04-07.log to the repository? - DELETED as per Slack convo
Where will be the log file dumped? Could we create a directory just for log files? - the logback file will create logs directory now as per slack convo

2017-04-11 17:03 UTC, Code4SocialGood commented
How to get a log file generated? I called getActiveUser API fromo http://localhost:8080/swagger-ui.html#!/user/getActiveUsersUsingGET, which calls  LOGGER.debug("**************All**************"); But I didn't get a log file generated locally.

![image](https://cloud.githubusercontent.com/assets/24813620/24920960/cd3c7502-1eae-11e7-92f1-6475eaf13a0f.png)

2017-04-13 13:15 UTC, n-machiavelli commented
This has been resolved. Note that you won't have "log.debug" in the log file as prod is set to INFO level. but if you have log.info for testing you will find it:
![image](https://cloud.githubusercontent.com/assets/5101665/25006124/472df304-2021-11e7-917c-44d5bb4c8209.png)

2017-04-14 03:10 UTC, Code4SocialGood commented
1. Are we using log4j2 or logback? The naming of 3 logging config files is confusing: log4j2.xml, logback-dev.xml, logback-prod.xml
2. Local Development Environment: After starting Spring Boot, a log file is generated: \logs\logFile.2017-04-13.log. Please change the config so that all the logging are sent to console. No log file for local dev.
3. Test server environment and Prod environment: Log level is DEBUG for test server and INFO for prod. Logging is sent to file appender. What do I need to change so that test/prod server config will be used?

2017-04-14 05:49 UTC, n-machiavelli commented
1. Are we using log4j2 or logback? We are using logback. The log4j2 file was there before and I have just removed it and retested.
2. I have fixed this in application-dev.properties. No log file for local dev.
3. This is setup by setting the appropriate logback file in the last line of application-dev.properties and application-prod.properties

![image](https://cloud.githubusercontent.com/assets/5101665/25034447/3560e68c-20ac-11e7-918f-e5b3622c1791.png)

![image](https://cloud.githubusercontent.com/assets/5101665/25034453/4460f41a-20ac-11e7-8c7d-20e941880d39.png)

2017-04-14 15:24 UTC, felipealvesgnu approved these changes

2017-04-14 15:30 UTC, merged