rest api - delete logo, delete resume, delete avatar
Code4SocialGood/c4sg-services pull request #195
Opened 2017-05-14 02:07 UTC by andykhoa

2017-05-14 16:22 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/ProjectController.java
> +    		projectService.updateProject(pr);
Can you create a delete method, instead of set null ??

2017-05-14 16:22 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/UserController.java
> +    		u.setAvatarUrl(null);
Can you create a delete method, instead of set null ?? again

2017-05-14 18:25 UTC, andykhoa commented on src/main/java/org/c4sg/controller/ProjectController.java
> +    		projectService.updateProject(pr);
In the DTO classes?

2017-05-17 01:48 UTC, felipealvesgnu requested changes

2017-05-17 01:48 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/ProjectController.java
>      public String deleteImage(@ApiParam(value = "Project id to delete image for", required = true)
This method is an UPDATE operation not a DELETE operation, because you're not deleting the resource just updating it. So change the this method.

2017-05-17 01:48 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/ProjectController.java
>      			return "Success";
Use `ResponseEntity.noContent().build();` in the return statement. You can take the method `getApplicants` in the `UserController` class as an example to help you.

2017-05-17 01:48 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/UserController.java
> +    			return "Success";
Use ResponseEntity.noContent().build(); in the return statement. You can take the method getApplicants in the UserController class as an example to help you.

2017-05-17 01:48 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/UserController.java
> +    @RequestMapping(value = "/{id}/avatar", method = RequestMethod.DELETE)
Change to a `PUT` method.

2017-05-17 01:48 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/UserController.java
> +    			return "Success";
Use ResponseEntity.noContent().build(); in the return statement. You can take the method getApplicants in the UserController class as an example to help you.

2017-05-17 01:49 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/ProjectController.java
>      public String deleteImage(@ApiParam(value = "Project id to delete image for", required = true)
http://www.concretepage.com/spring-4/spring-4-mvc-responseentity-bodybuilder-responseentity-enhancements-example

2017-05-17 02:32 UTC, closed without merging