commit corrections search organization
Code4SocialGood/c4sg-services pull request #202
Opened 2017-05-20 22:22 UTC by JayGibran

Corrections in organization search. 
It was added new parameters to method and query.

2017-05-21 20:37 UTC, felipealvesgnu requested changes

2017-05-21 20:37 UTC, felipealves-gnu commented on src/main/java/org/c4sg/dao/OrganizationDAO.java
> +    String FIND_BY_KEYWORD_COUNTRIES_OPORTUNITES = "SELECT DISTINCT o FROM Project p INNER JOIN p.organization o " +
Delete those FIND_BY..... and replace by Query methods as mentioned here: https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.query-creation

2017-05-21 20:37 UTC, felipealves-gnu commented on src/main/java/org/c4sg/service/impl/OrganizationServiceImpl.java
> +    		organizationDAO.save(organization);
Why are you calling `organizationDAO.save(organization)` method if the method is called `deleteOrganization(int i)` ?

2017-05-22 00:01 UTC, JayGibran commented on src/main/java/org/c4sg/dao/OrganizationDAO.java
> +    String FIND_BY_KEYWORD_COUNTRIES_OPORTUNITES = "SELECT DISTINCT o FROM Project p INNER JOIN p.organization o " +
Hi Felipe, do you talk about remove static strings and use directly in the query.

2017-05-22 14:40 UTC, felipealves-gnu commented on src/main/java/org/c4sg/dao/OrganizationDAO.java
> +    String FIND_BY_KEYWORD_COUNTRIES_OPORTUNITES = "SELECT DISTINCT o FROM Project p INNER JOIN p.organization o " +
Hi..No, I said to use the query creation mechanism as mentioned in the link I attached to you. You can follow the examples that we have in the project as well.

2017-05-24 20:52 UTC, joshisayali reviewed
queries FIND_BY_KEYWORD and FIND_BY_KEYWORD_COUNTRIES are returning wrong results. As per my understanding, it should return all the organizations with or without opportunities. Please get it clarified. Also please get clarified what should be the query result when open = true, open = false and value for open is not provided.

2017-05-30 17:52 UTC, felipealves-gnu commented
@JayGibran are you able to fix those codes ?

2017-05-30 17:52 UTC, closed without merging