Rest API - Feed to AllForGood #6
Code4SocialGood/c4sg-services pull request #298
Opened 2017-07-17 03:34 UTC by soham1

The lack of certain fields has led me to create default values. When the
new fields are added and populated, we will need another issue for
adding those into the AllForGood feed. Please also refer to the TODO
comments I have left.

2017-07-18 13:26 UTC, felipealvesgnu submitted a review, later dismissed

2017-07-18 13:26 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/AllForGoodFeedController.java
> +    @RequestMapping(method = RequestMethod.GET, produces = MediaType.APPLICATION_XML_VALUE)
Why are you using XML and not JSON returning ?

2017-07-18 13:26 UTC, felipealves-gnu commented on src/main/java/org/c4sg/dto/afg/FeedDTO.java
> +@XmlRootElement(name = "FootprintFeed")
Use JSON not XML

2017-07-18 13:26 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/AllForGoodFeedController.java
> +		for (OrganizationDTO o : organizations) {
Try to break in more methods. You have too much lines to an only method.

2017-07-18 13:26 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/AllForGoodFeedController.java
> +		List<ProjectDTO> projects = new ArrayList<ProjectDTO>();
If you use JSON instead of XML I believe a bunch of these line will disappear!

2017-07-18 14:28 UTC, soham1 commented on src/main/java/org/c4sg/controller/AllForGoodFeedController.java
> +		for (OrganizationDTO o : organizations) {
Ok, I will create more methods.

2017-07-18 14:30 UTC, soham1 commented on src/main/java/org/c4sg/controller/AllForGoodFeedController.java
> +    @RequestMapping(method = RequestMethod.GET, produces = MediaType.APPLICATION_XML_VALUE)
There is almost no documentation for returning JSON on the AllForFeed site. Here is the link tho their documentation: http://allforgoodorg.devcloud.acquia-sites.com/feed-specification

2017-07-24 00:44 UTC, Code4SocialGood commented
@soham1 What is the link for All for Good data feed API?

2017-07-24 00:46 UTC, soham1 commented
This is the link: http://allforgoodorg.devcloud.acquia-sites.com/feed-specification

2017-07-24 01:37 UTC, felipealves-gnu commented
Hi, Create new class inside #service# package called #FeedService# and put all the other methods over there, less #getProjects#.

2017-08-18 03:19 UTC, soham1 commented
Sorry for the late update. I had a few urgent problems to attend. I have created a new commit fulfilling the new requirements.

2017-08-21 14:56 UTC, Code4SocialGood commented
@soham1 Could you please resolve the conflicts?

2017-08-21 16:06 UTC, soham1 commented
Conflicts have been resolved.

2017-08-22 01:55 UTC, felipealvesgnu requested changes

2017-08-22 01:55 UTC, felipealves-gnu commented on src/main/java/org/c4sg/service/FeedService.java
> +public class FeedService {
Could you create some tests to those methods ?

2017-08-22 11:04 UTC, felipealves-gnu commented on src/main/java/org/c4sg/service/FeedService.java
> +public class FeedService {
I'm getting a lot of conflicts as well in 3 classes: OrganizationDTO, WebSecurityConfig and JwUtil.

2017-08-22 13:44 UTC, soham1 commented on src/main/java/org/c4sg/service/FeedService.java
> +public class FeedService {
Yeah, Travis Errors say that all the variables are already defined in class OrganizationDTO...

2017-08-25 10:00 UTC, felipealves-gnu commented on src/main/java/org/c4sg/service/FeedService.java
> +public class FeedService {
But those errors happens because you're declaring variables with same name twice !!!

2017-11-21 16:17 UTC, closed without merging