Added services to return count
Code4SocialGood/c4sg-services pull request #415
Opened 2018-03-24 10:39 UTC by sumantsahney

Added services to return count

2018-03-24 10:40 UTC, sumantsahney commented
Can you please review it ?

2018-04-08 19:13 UTC, Code4SocialGood reviewed
1. Could you please remove file: c4sg-services.iml
2. Do we need to use native query for count?
3. The method signature for controller: do we need to use map? can we simply return the count?

2018-04-11 19:42 UTC, felipealvesgnu requested changes

2018-04-11 19:42 UTC, felipealvesgnu commented on c4sg-services.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Don't commit this file, delete it

2018-04-11 19:42 UTC, felipealvesgnu commented on src/main/java/org/c4sg/controller/OrganizationController.java
> +		HashMap<String, String> map = new HashMap<>();
As a rule of polymorphism.
Use `Map<String, String> map = new HashMap<>();`

2018-04-11 19:42 UTC, felipealvesgnu commented on src/main/java/org/c4sg/controller/ProjectController.java
> +        HashMap<String, String> map = new HashMap<>();
Use `Map<String, String> map = new HashMap<>();`

2018-04-11 19:42 UTC, felipealvesgnu commented on src/main/java/org/c4sg/controller/UserController.java
> +        HashMap<String, String> map = new HashMap<>();
Use` Map<String, String> map = new HashMap<>();`

2018-05-24 18:14 UTC, closed without merging