Create project bugfix
Code4SocialGood/c4sg-services pull request #85
Opened 2017-03-30 16:54 UTC by karthijey

2017-03-31 23:09 UTC, felipealvesgnu requested changes

2017-03-31 23:09 UTC, felipealvesgnu commented on src/main/java/org/c4sg/dao/ProjectDAO.java
> +    String FIND_BY_NAME_ORGANIZATION_ID = "SELECT p FROM Project p WHERE p.name =:name AND p.organization.id=:orgId";
Delete this line and create just method using Spring Data JPA check it out: http://docs.spring.io/spring-data/jpa/docs/1.4.1.RELEASE/reference/html/jpa.repositories.html

2017-03-31 23:09 UTC, felipealves-gnu commented on src/main/java/org/c4sg/entity/Project.java
> +@Table(name = "project")
It's redundant we don't need that

2017-03-31 23:09 UTC, felipealves-gnu commented on src/main/java/org/c4sg/dao/ProjectDAO.java
> +	Project findByNameOrganizationId(@Param("name")String name,  @Param("orgId") Integer orgId);
Replace with a method using Spring Data JPA

2017-04-01 14:49 UTC, karthijey commented
@felipealves-gnu I have made the changes using Spring data JPA. Please review the changes. Thanks.

2017-04-02 02:08 UTC, felipealvesgnu requested changes

2017-04-02 02:08 UTC, felipealvesgnu commented on src/main/java/org/c4sg/entity/Project.java
>  	@Value("${var.string:#{NULL}}")
Why Are you trying to use this line. We don't need it. you can delete.
Delete from `createdTime` inside `Organization.java` as well.

2017-04-02 02:08 UTC, felipealves-gnu commented on src/main/java/org/c4sg/dto/CreateProjectDTO.java
> +	private char remoteFlag;// possible values Y or N
You need to use String here, otherwise it won't work

2017-04-02 02:08 UTC, felipealves-gnu commented on src/main/java/org/c4sg/controller/ProjectController.java
> +
Cut this blank line and ident correctly

2017-04-02 17:02 UTC, karthijey commented on src/main/java/org/c4sg/entity/Project.java
>  	@Value("${var.string:#{NULL}}")
You mean this line, @Value("${var.string:#{NULL}}") ?

2017-04-03 18:40 UTC, felipealves-gnu commented on src/main/java/org/c4sg/entity/Project.java
>  	@Value("${var.string:#{NULL}}")
yes

2017-04-03 20:43 UTC, karthijey commented on src/main/java/org/c4sg/entity/Project.java
>  	@Value("${var.string:#{NULL}}")
Please check issue # 75 fix #87. It's from that code change. Do you want to remove it from all 3 files: Project, Organization and User.java?

2017-04-04 00:27 UTC, felipealves-gnu commented on src/main/java/org/c4sg/entity/Project.java
>  	@Value("${var.string:#{NULL}}")
Do you have any reason to use that ? Did you test the code with and without this annotation ?

2017-04-04 14:02 UTC, karthijey commented on src/main/java/org/c4sg/entity/Project.java
>  	@Value("${var.string:#{NULL}}")
Done. We don't need that line of code. Thanks.

2017-04-04 14:54 UTC, felipealvesgnu approved these changes

2017-04-04 14:55 UTC, merged